CREATE TABLE Users(
	ID INTEGER PRIMARY KEY,
	FirstName TEXT,
	LastName TEXT,
	Email TEXT
);

CREATE TABLE Tasks(
	ID INTEGER PRIMARY KEY,
	UserID INTEGER NOT NULL,
	TaskType TEXT,
	Completed BIT,
	ShortDesc TEXT,
	DateStart DATE,
	DateEnd DATE
);


CREATE TABLE TaskInfos(
	ID INTEGER PRIMARY KEY,
	Field1 TEXT,
	Field2 INTEGER,
	Field3 BIT,
	Field4 TEXT
);